link_index:
    path:     /
    defaults: { _controller: "YoupiBundle:Link:index" }
    methods:  GET

link_show:
    path:     /{id}/show
    defaults: { _controller: "YoupiBundle:Link:show" }
    methods:  GET

link_new:
    path:     /new
    defaults: { _controller: "YoupiBundle:Link:new" }
    methods:  [GET, POST]

link_edit:
    path:     /{id}/edit
    defaults: { _controller: "YoupiBundle:Link:edit" }
    methods:  [GET, POST]

link_delete:
    path:     /{id}/delete
    defaults: { _controller: "YoupiBundle:Link:delete" }
    methods:  DELETE
