user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

fos_user_profile_show_name:
  path: /profil/{id}
  defaults: { _controller: FOSUserBundle:Profile:show }
  requirements:
        _method:  GET
        id: \d+
